import numpy as np
import pandas as pd
from ta.volatility import AverageTrueRange

class FeatureEngineer:
    """Computes pure volatility features for the HMM Regime Engine."""
    
    @staticmethod
    def add_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
        """
        Add volatility-centric features to the DataFrame.
        Assumes df contains: 'open', 'high', 'low', 'close', 'volume'
        Returns a new DataFrame with features appended.
        """
        # Ensure we don't modify the original dataframe
        df = df.copy()
        
        # 1. Log Returns: Fundamental measure of price step magnitude
        df['log_return'] = np.log(df['close'] / df['close'].shift(1))
        
        # 2. Realized Volatility: Rolling standard deviation of log returns
        # We calculate short (12 bars) and long (24 bars) realized volatility
        df['rv_12'] = df['log_return'].rolling(window=12).std() * np.sqrt(24 * 365) # Annualized (assuming 1h bars)
        df['rv_24'] = df['log_return'].rolling(window=24).std() * np.sqrt(24 * 365)
        
        # 3. Normalized ATR (Average True Range)
        # We use a 14-bar ATR, but divide by close price to normalize it across different cryptos
        atr_indicator = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'], window=14)
        df['atr_14'] = atr_indicator.average_true_range()
        df['atr_normalized'] = df['atr_14'] / df['close']
        
        # 4. Garman-Klass Volatility: Uses High, Low, Open, Close for a robust volatility estimate
        # Formula: 0.5 * [log(High/Low)]^2 - (2*log(2) - 1) * [log(Close/Open)]^2
        log_hl = np.log(df['high'] / df['low'])
        log_co = np.log(df['close'] / df['open'])
        df['gk_vol'] = np.sqrt(0.5 * log_hl**2 - (2 * np.log(2) - 1) * log_co**2)
        
        # Rolling Garman-Klass (e.g., 24 bars)
        df['gk_vol_24'] = df['gk_vol'].rolling(window=24).mean() * np.sqrt(24 * 365)
        
        # Drop NaN values generated by rolling windows
        df.dropna(inplace=True)
        
        return df

    @staticmethod
    def extract_hmm_features(df: pd.DataFrame) -> np.ndarray:
        """
        Extract the exact features needed to train/predict with the HMM.
        Returns a 2D numpy array shaped (n_samples, n_features).
        """
        # We select features that strictly describe volatility/regime, NOT direction.
        # Notice we take the ABSOLUTE value of log return, or we could leave it 
        # (since Gaussians capture mean and variance), but rv_12, rv_24, and gk_vol_24 are best.
        
        features = ['rv_12', 'rv_24', 'atr_normalized', 'gk_vol_24']
        return df[features].values

